apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-attachments-pvc
spec:
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: client-attachments-pvc
spec:
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-avatars-pvc
spec:
  resources:
    requests:
      storage: 10Gi
