apiVersion: v1
kind: Secret
metadata:
  name: task-tracker-secrets

type: Opaque
stringData:
  JWT_SECRET: replace-with-strong-secret
  AUTH_DB_PASSWORD: auth
  USER_DB_PASSWORD: user
  TASK_DB_PASSWORD: task
  CLIENT_DB_PASSWORD: client
  GOOGLE_CLIENT_ID: replace-me
  GOOGLE_CLIENT_SECRET: replace-me
