apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: USER_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: task-tracker-config
                  key: USER_DB_URL
            - name: USER_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: task-tracker-config
                  key: USER_DB_USER
            - name: USER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-tracker-secrets
                  key: USER_DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: task-tracker-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8082
      targetPort: 8082
      name: http
  type: ClusterIP
