apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: taskflow-cluster-secret-store
spec:
  provider:
    vault:
      server: https://vault.example.com
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: taskflow
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
