server:
  port: ${USER_PORT:8082}

spring:
  application:
    name: user-service
  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://user-db:5432/user_db}
    username: ${USER_DB_USER:user}
    password: ${USER_DB_PASSWORD:user}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET:change-me}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
