apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: task-tracker-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: taskflow-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: task-tracker-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: taskflow/stage/api
        property: JWT_SECRET
    - secretKey: INTERNAL_API_TOKEN
      remoteRef:
        key: taskflow/stage/api
        property: INTERNAL_API_TOKEN
    - secretKey: AUTH_DB_PASSWORD
      remoteRef:
        key: taskflow/stage/databases
        property: AUTH_DB_PASSWORD
    - secretKey: USER_DB_PASSWORD
      remoteRef:
        key: taskflow/stage/databases
        property: USER_DB_PASSWORD
    - secretKey: TASK_DB_PASSWORD
      remoteRef:
        key: taskflow/stage/databases
        property: TASK_DB_PASSWORD
    - secretKey: CLIENT_DB_PASSWORD
      remoteRef:
        key: taskflow/stage/databases
        property: CLIENT_DB_PASSWORD
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: taskflow/stage/oauth
        property: GOOGLE_CLIENT_ID
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: taskflow/stage/oauth
        property: GOOGLE_CLIENT_SECRET
    - secretKey: APP_BOOTSTRAP_ADMIN_EMAIL
      remoteRef:
        key: taskflow/stage/bootstrap
        property: APP_BOOTSTRAP_ADMIN_EMAIL
    - secretKey: APP_BOOTSTRAP_ADMIN_PASSWORD
      remoteRef:
        key: taskflow/stage/bootstrap
        property: APP_BOOTSTRAP_ADMIN_PASSWORD
