{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskflow.secretName" . }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  INTERNAL_API_TOKEN: {{ .Values.secrets.internalApiToken | quote }}
  AUTH_DB_PASSWORD: {{ .Values.secrets.databasePasswords.auth | quote }}
  USER_DB_PASSWORD: {{ .Values.secrets.databasePasswords.user | quote }}
  TASK_DB_PASSWORD: {{ .Values.secrets.databasePasswords.task | quote }}
  CLIENT_DB_PASSWORD: {{ .Values.secrets.databasePasswords.client | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
  APP_BOOTSTRAP_ADMIN_EMAIL: {{ .Values.secrets.bootstrapAdminEmail | quote }}
  APP_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.secrets.bootstrapAdminPassword | quote }}
{{- end }}
