{{- range $key, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  labels:
    {{- include "taskflow.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $svc.name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $svc.name }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: http
{{- end }}
