apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - auth-service.yaml
  - user-service.yaml
  - task-service.yaml
  - client-service.yaml
  - api-gateway.yaml
  - networkpolicy-default-deny.yaml
  - networkpolicy-internal.yaml
